# Generated by Django 4.2.7 on 2025-10-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='achievement',
            new_name='achievement_user_id_13159a_idx',
            old_name='achievement_user_id_f3c92a_idx',
        ),
        migrations.RenameIndex(
            model_name='achievement',
            new_name='achievement_badge_i_da0a36_idx',
            old_name='achievement_badge_i_e91ad3_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardcache',
            new_name='dashboard_c_user_id_f25fd8_idx',
            old_name='dashboard_c_user_id_5e8ed7_idx',
        ),
        migrations.RenameIndex(
            model_name='dashboardcache',
            new_name='dashboard_c_expires_df6b23_idx',
            old_name='dashboard_c_expires_bb5a68_idx',
        ),
        migrations.RenameIndex(
            model_name='recipecookinglog',
            new_name='recipe_cook_user_id_3e8daf_idx',
            old_name='recipe_cook_user_id_d15f6e_idx',
        ),
        migrations.RenameIndex(
            model_name='recipecookinglog',
            new_name='recipe_cook_recipe__7db3ec_idx',
            old_name='recipe_cook_recipe__dac9ab_idx',
        ),
        migrations.RenameIndex(
            model_name='userstreak',
            new_name='user_streak_user_id_f67807_idx',
            old_name='user_streak_user_id_c2c15a_idx',
        ),
    ]
