# Generated by Django 4.2.7 on 2025-10-24 10:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0002_rename_achievement_user_id_f3c92a_idx_achievement_user_id_13159a_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboardcache',
            name='dashboard_c_user_id_f25fd8_idx',
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcache',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dashboardcache',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('ru', 'Russian')], default='en', help_text='Language for cached content', max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='dashboardcache',
            unique_together={('user', 'period', 'language')},
        ),
        migrations.AddIndex(
            model_name='dashboardcache',
            index=models.Index(fields=['user', 'period', 'language'], name='dashboard_c_user_id_3bdba1_idx'),
        ),
    ]
