# Generated by Django 4.2.7 on 2025-10-25 19:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRateLimitSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_recipes_per_minute', models.IntegerField(default=5)),
                ('max_recipes_per_day', models.IntegerField(default=25)),
                ('exempted_users', models.TextField(default='testuser1,testuser2', help_text='Comma-separated list of usernames exempt from rate limits')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Rate Limit Settings',
                'verbose_name_plural': 'AI Rate Limit Settings',
                'db_table': 'ai_rate_limit_settings',
            },
        ),
        migrations.CreateModel(
            name='AIRateLimitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(default='recipe_generation', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('recipes_generated', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_rate_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_rate_limit_log',
                'indexes': [models.Index(fields=['user', 'timestamp'], name='ai_rate_lim_user_id_5a9ae2_idx'), models.Index(fields=['endpoint', 'timestamp'], name='ai_rate_lim_endpoin_7d1f42_idx')],
            },
        ),
    ]
