# Generated by Django 4.2.16 on 2026-05-29 06:29

import branding.models
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_name_en', models.CharField(default='BishulSheli', max_length=100)),
                ('site_name_ru', models.CharField(default='BishulSheli', max_length=100)),
                ('site_name_he', models.CharField(default='בישול שלי', max_length=100)),
                ('primary_color', models.CharField(default='#9B59B6', help_text='Primary brand color (hex code)', max_length=7)),
                ('secondary_color', models.CharField(default='#8E44AD', help_text='Secondary brand color (hex code)', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'db_table': 'site_settings',
            },
        ),
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('logo_type', models.CharField(choices=[('navbar_desktop', 'Navbar Logo (Desktop)'), ('navbar_mobile', 'Navbar Logo (Mobile)'), ('login_page', 'Login Page Logo'), ('favicon', 'Favicon (Browser Tab)'), ('app_icon', 'App Icon (PWA)')], help_text='Where this logo will be displayed', max_length=20)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew'), ('all', 'All Languages (Default)')], default='all', help_text='Language for this logo (use "All Languages" for universal logos)', max_length=5)),
                ('image_file', models.FileField(help_text='Upload logo file (SVG recommended for best quality)', upload_to=branding.models.logo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp', 'ico'])])),
                ('alt_text', models.CharField(default='BishulSheli', help_text='Alternative text for accessibility', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Set to active to use this logo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.CharField(blank=True, help_text='Admin username who uploaded the logo', max_length=100)),
                ('width', models.PositiveIntegerField(blank=True, help_text='Logo width in pixels (auto-detected)', null=True)),
                ('height', models.PositiveIntegerField(blank=True, help_text='Logo height in pixels (auto-detected)', null=True)),
                ('file_size', models.PositiveIntegerField(blank=True, help_text='File size in bytes (auto-detected)', null=True)),
            ],
            options={
                'verbose_name': 'Site Logo',
                'verbose_name_plural': 'Site Logos',
                'db_table': 'site_logos',
                'ordering': ['logo_type', 'language_code', '-updated_at'],
                'indexes': [models.Index(fields=['logo_type', 'language_code', 'is_active'], name='site_logos_logo_ty_c00f85_idx')],
                'unique_together': {('logo_type', 'language_code')},
            },
        ),
    ]
