version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: menumine_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend_build:/usr/share/nginx/html:ro
      - backend_static:/app/staticfiles:ro
      - ./backend/media:/app/media:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - menumine_network

volumes:
  backend_static:
    external: true
    name: menumind_ai_backend_static

networks:
  menumine_network:
    external: true
    name: menumind_ai_menumine_network
