# Generated by Django 4.2.7 on 2025-10-03 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rcip_version', models.CharField(default='0.1', max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('ingredients', models.JSONField(default=list)),
                ('steps', models.JSONField(default=list)),
                ('author', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True)),
                ('total_time_minutes', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(default=4)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('diet_labels', models.JSONField(default=list)),
                ('recipe_hash', models.CharField(db_index=True, max_length=64)),
                ('version', models.IntegerField(default=1)),
                ('is_latest_version', models.BooleanField(default=True)),
                ('times_added_to_lists', models.IntegerField(default=0)),
                ('times_cooked', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recipes', to=settings.AUTH_USER_MODEL)),
                ('parent_recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='recipes.recipe')),
            ],
            options={
                'db_table': 'recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True)),
                ('times_cooked', models.IntegerField(default=0)),
                ('last_cooked', models.DateTimeField(blank=True, null=True)),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_recipes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_recipes',
                'indexes': [models.Index(fields=['user', '-saved_at'], name='user_recipe_user_id_abf561_idx')],
                'unique_together': {('user', 'recipe')},
            },
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['name', 'recipe_hash'], name='recipes_name_cd043a_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['created_by', '-created_at'], name='recipes_created_35c4dc_idx'),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['is_latest_version'], name='recipes_is_late_6f846c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipe',
            unique_together={('recipe_hash', 'version')},
        ),
    ]
