# Generated by Django 4.2.7 on 2025-10-07 08:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


def migrate_recipes_to_canonical(apps, schema_editor):
    """
    Data migration: Convert existing Recipe instances to CanonicalRecipe + user forks.

    Strategy:
    1. Group recipes by recipe_hash (unique dishes)
    2. For each unique hash, create ONE CanonicalRecipe
    3. Convert all Recipe instances with that hash to user forks
    """
    Recipe = apps.get_model('recipes', 'Recipe')
    CanonicalRecipe = apps.get_model('recipes', 'CanonicalRecipe')

    # Get all recipes
    all_recipes = Recipe.objects.all().select_related('created_by')

    if not all_recipes.exists():
        print("[MIGRATION] No recipes to migrate.")
        return

    # Group recipes by hash
    recipe_groups = {}
    for recipe in all_recipes:
        hash_key = recipe.recipe_hash
        if hash_key not in recipe_groups:
            recipe_groups[hash_key] = []
        recipe_groups[hash_key].append(recipe)

    print(f"[MIGRATION] Found {len(recipe_groups)} unique recipes (by hash)")

    # Create canonical recipes
    canonical_map = {}  # recipe_hash -> CanonicalRecipe

    for recipe_hash, recipe_list in recipe_groups.items():
        # Use the first recipe as the base for canonical
        base_recipe = recipe_list[0]

        # Create canonical recipe
        try:
            canonical = CanonicalRecipe.objects.create(
                name=base_recipe.name,
                description=base_recipe.description,
                source_type='ai_generated',  # All existing recipes came from AI
                ai_source_url=base_recipe.source_url,
                original_creator=base_recipe.created_by,
                base_ingredients=base_recipe.ingredients,
                base_steps=base_recipe.steps,
                cuisine=base_recipe.cuisine,
                difficulty=base_recipe.difficulty,
                diet_labels=base_recipe.diet_labels,
                prep_time_minutes=base_recipe.prep_time_minutes,
                cook_time_minutes=base_recipe.cook_time_minutes,
                total_time_minutes=base_recipe.total_time_minutes,
                servings=base_recipe.servings,
                recipe_hash=base_recipe.recipe_hash,
                created_at=base_recipe.created_at,
                updated_at=base_recipe.updated_at
            )
            canonical_map[recipe_hash] = canonical
            print(
                f"[MIGRATION] Created canonical: {canonical.name} (hash: {recipe_hash[:8]}...)")
        except Exception as e:
            print(
                f"[MIGRATION ERROR] Failed to create canonical for {base_recipe.name}: {e}")
            continue

    # Convert recipes to forks
    fork_count = 0
    for recipe in all_recipes:
        canonical = canonical_map.get(recipe.recipe_hash)
        if not canonical:
            continue

        # Convert to fork
        recipe.canonical_recipe = canonical
        recipe.is_fork = True
        recipe.user_modifications = {}  # Start with no modifications
        recipe.save(update_fields=['canonical_recipe',
                    'is_fork', 'user_modifications'])

        fork_count += 1

    # Update canonical statistics
    for canonical in canonical_map.values():
        fork_count_for_canonical = canonical.user_forks.count()
        total_cooked = sum(
            fork.times_cooked for fork in canonical.user_forks.all())

        canonical.total_saves = fork_count_for_canonical
        canonical.total_cooked = total_cooked
        canonical.save(update_fields=['total_saves', 'total_cooked'])

    print(f"[MIGRATION] Converted {fork_count} recipes to forks")
    print(f"[MIGRATION] Created {len(canonical_map)} canonical recipes")
    print("[MIGRATION] Migration complete!")


def reverse_migration(apps, schema_editor):
    """Reverse migration: Convert forks back to standalone recipes"""
    Recipe = apps.get_model('recipes', 'Recipe')
    CanonicalRecipe = apps.get_model('recipes', 'CanonicalRecipe')

    # Reset fork status
    Recipe.objects.filter(is_fork=True).update(
        canonical_recipe=None,
        is_fork=False,
        user_modifications={}
    )

    # Delete all canonical recipes
    CanonicalRecipe.objects.all().delete()

    print("[MIGRATION] Reversed migration - deleted canonical recipes")


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanonicalRecipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('ai_generated', 'AI Generated'), ('user_created', 'User Created'), (
                    'community_curated', 'Community Curated')], default='ai_generated', max_length=20)),
                ('ai_source_url', models.URLField(blank=True, null=True)),
                ('base_ingredients', models.JSONField(default=list)),
                ('base_steps', models.JSONField(default=list)),
                ('cuisine', models.CharField(blank=True, max_length=100)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), (
                    'intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=20)),
                ('diet_labels', models.JSONField(default=list)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True)),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True)),
                ('total_time_minutes', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(default=4)),
                ('recipe_hash', models.CharField(
                    db_index=True, max_length=64, unique=True)),
                ('total_saves', models.IntegerField(default=0)),
                ('total_cooked', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(
                    decimal_places=2, default=0, max_digits=3)),
                ('total_ratings', models.IntegerField(default=0)),
                ('total_reviews', models.IntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'canonical_recipes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recipe_likes',
            },
        ),
        migrations.CreateModel(
            name='RecipeRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[
                 (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe_ratings',
            },
        ),
        migrations.CreateModel(
            name='RecipeReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[
                 (1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('helpful_count', models.IntegerField(default=0)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recipe_reviews',
            },
        ),
        migrations.CreateModel(
            name='RecipeReviewHelpful',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'recipe_review_helpful',
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='is_fork',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user_modifications',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='recipereviewhelpful',
            name='review',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='marked_helpful_by', to='recipes.recipereview'),
        ),
        migrations.AddField(
            model_name='recipereviewhelpful',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='helpful_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='canonical_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='reviews', to='recipes.canonicalrecipe'),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipe_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reciperating',
            name='canonical_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ratings', to='recipes.canonicalrecipe'),
        ),
        migrations.AddField(
            model_name='reciperating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipe_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipelike',
            name='canonical_recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='likes', to='recipes.canonicalrecipe'),
        ),
        migrations.AddField(
            model_name='recipelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='recipe_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='canonicalrecipe',
            name='original_creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='canonical_recipes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recipe',
            name='canonical_recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='user_forks', to='recipes.canonicalrecipe'),
        ),
        # Add index AFTER canonical_recipe field is created
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(
                fields=['canonical_recipe', 'is_fork'], name='recipes_canonic_f2d3f4_idx'),
        ),
        migrations.AddIndex(
            model_name='recipereviewhelpful',
            index=models.Index(
                fields=['review', '-created_at'], name='recipe_revi_review__c2fb53_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipereviewhelpful',
            unique_together={('user', 'review')},
        ),
        migrations.AddIndex(
            model_name='recipereview',
            index=models.Index(fields=[
                               'canonical_recipe', '-helpful_count'], name='recipe_revi_canonic_1b5cc2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipereview',
            index=models.Index(
                fields=['canonical_recipe', '-created_at'], name='recipe_revi_canonic_d17b91_idx'),
        ),
        migrations.AddIndex(
            model_name='recipereview',
            index=models.Index(fields=['-created_at'],
                               name='recipe_revi_created_6e5d92_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipereview',
            unique_together={('user', 'canonical_recipe')},
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(
                fields=['canonical_recipe', '-rating'], name='recipe_rati_canonic_59f59a_idx'),
        ),
        migrations.AddIndex(
            model_name='reciperating',
            index=models.Index(
                fields=['user', '-created_at'], name='recipe_rati_user_id_c045c5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reciperating',
            unique_together={('user', 'canonical_recipe')},
        ),
        migrations.AddIndex(
            model_name='recipelike',
            index=models.Index(
                fields=['canonical_recipe', '-created_at'], name='recipe_like_canonic_ca6be2_idx'),
        ),
        migrations.AddIndex(
            model_name='recipelike',
            index=models.Index(
                fields=['user', '-created_at'], name='recipe_like_user_id_24be32_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recipelike',
            unique_together={('user', 'canonical_recipe')},
        ),
        migrations.AddIndex(
            model_name='canonicalrecipe',
            index=models.Index(
                fields=['name', 'recipe_hash'], name='canonical_r_name_b1a30b_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrecipe',
            index=models.Index(fields=['source_type'],
                               name='canonical_r_source__1ac87a_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrecipe',
            index=models.Index(
                fields=['-average_rating', '-total_saves'], name='canonical_r_average_935e35_idx'),
        ),
        migrations.AddIndex(
            model_name='canonicalrecipe',
            index=models.Index(fields=['-created_at'],
                               name='canonical_r_created_979b00_idx'),
        ),
        # Run data migration to convert existing recipes
        migrations.RunPython(migrate_recipes_to_canonical, reverse_migration),
    ]
