# Generated by Django 4.2.7 on 2025-10-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_add_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_source_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_cuisine_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_diff_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_pub_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_pub_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_pub_saves_idx',
        ),
        migrations.RemoveIndex(
            model_name='canonicalrecipe',
            name='recipes_can_pub_cooked_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipe',
            name='recipes_rec_user_fork_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipelike',
            name='recipes_like_user_recipe_idx',
        ),
        migrations.RemoveIndex(
            model_name='reciperating',
            name='recipes_rate_user_recipe_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipereview',
            name='recipes_rev_recipe_date_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipereview',
            name='recipes_rev_recipe_help_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipereview',
            name='recipes_rev_recipe_rating_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipereview',
            name='recipes_rev_approved_idx',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='recipe_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
