# Generated by Django 4.2.7 on 2025-10-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_allow_null_recipe_hash_for_forks'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrecipe',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userrecipe',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
