# Generated by Django 4.2.7 on 2025-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_add_archive_to_user_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='canonicalrecipe',
            name='description_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Description translations for each language'),
        ),
        migrations.AddField(
            model_name='canonicalrecipe',
            name='nutrition_per_serving',
            field=models.JSONField(blank=True, default=dict, help_text='Nutrition calculated from IML: {calories: 380, protein: 26, fat: 15, carbs: 32, fiber: 4}'),
        ),
        migrations.AddField(
            model_name='canonicalrecipe',
            name='original_language',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], default='en', help_text='Language in which recipe was originally created', max_length=2),
        ),
        migrations.AddField(
            model_name='canonicalrecipe',
            name='steps_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Steps translations: {en: [{step_number: 1, instruction: "..."}], ru: [...], he: [...]}'),
        ),
        migrations.AddField(
            model_name='canonicalrecipe',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translations: {en: "Ukrainian Borscht", ru: "Украинский борщ", he: "בורשט אוקראיני"}'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='title_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Title translations if user renames fork: {en: "...", ru: "...", he: "..."}'),
        ),
    ]
