# Generated by Django 4.2.7 on 2025-10-20 17:52

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_canonicalrecipe_description_translations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], db_index=True, max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('base_ingredients', models.JSONField(default=list, help_text='Translated ingredients')),
                ('base_steps', models.JSONField(default=list, help_text='Translated cooking steps')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('canonical_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='recipes.canonicalrecipe')),
            ],
            options={
                'db_table': 'recipe_translations',
                'indexes': [models.Index(fields=['canonical_recipe', 'language'], name='recipe_tran_canonic_084b3e_idx'), models.Index(fields=['status'], name='recipe_tran_status_79ae77_idx'), models.Index(fields=['language', 'status'], name='recipe_tran_languag_6e2428_idx')],
                'unique_together': {('canonical_recipe', 'language')},
            },
        ),
    ]
