# Generated by Django 4.2.7 on 2025-10-21 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipetranslation',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
    ]
