# Generated by Django for MenuMine AI - Sprint 1
# Discovery Cache for fast recipe card loading

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_add_translation_name_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscoveryCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('language', models.CharField(
                    choices=[('en', 'English'), ('ru', 'Russian'),
                             ('he', 'Hebrew')],
                    db_index=True,
                    max_length=2,
                    help_text='Language code for this cached entry'
                )),
                ('title', models.CharField(
                    db_index=True,
                    max_length=200,
                    help_text='Translated recipe title for quick display'
                )),
                ('brief', models.TextField(
                    help_text='Short description (first 200 chars) for preview'
                )),
                ('image_url', models.URLField(
                    blank=True,
                    null=True,
                    help_text='Recipe image URL'
                )),
                ('tags', models.JSONField(
                    default=list,
                    help_text='Recipe tags for filtering'
                )),
                ('cached_at', models.DateTimeField(
                    auto_now=True,
                    help_text='Last time this cache entry was updated'
                )),
                ('created_at', models.DateTimeField(
                    auto_now_add=True,
                    help_text='When this cache entry was created'
                )),
                ('canonical_recipe', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='discovery_cache_entries',
                    to='recipes.canonicalrecipe',
                    help_text='Reference to the canonical recipe'
                )),
            ],
            options={
                'db_table': 'discovery_cache',
                'verbose_name': 'Discovery Cache Entry',
                'verbose_name_plural': 'Discovery Cache Entries',
                'ordering': ['-cached_at'],
                'indexes': [
                    models.Index(
                        fields=['language', '-cached_at'], name='discovery_lang_time_idx'),
                    models.Index(
                        fields=['canonical_recipe', 'language'], name='discovery_recipe_lang_idx'),
                    models.Index(fields=['-cached_at'],
                                 name='discovery_time_idx'),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name='discoverycache',
            constraint=models.UniqueConstraint(
                fields=['canonical_recipe', 'language'],
                name='unique_recipe_language_cache'
            ),
        ),
    ]
