# Generated by Django for MenuMine AI - Sprint 1
# Add enhanced performance indexes for translation queries
# SQLite-compatible version

from django.db import migrations, models


def create_postgresql_indexes(apps, schema_editor):
    """Create PostgreSQL-specific indexes if using PostgreSQL"""
    if schema_editor.connection.vendor == 'postgresql':
        # Enable pg_trgm extension
        schema_editor.execute('CREATE EXTENSION IF NOT EXISTS pg_trgm;')

        # Create GIN index for fast multilingual search
        schema_editor.execute('''
            CREATE INDEX IF NOT EXISTS recipe_translation_name_trgm_idx 
            ON recipe_translations USING gin (name gin_trgm_ops);
        ''')
        print("✅ Created PostgreSQL trigram indexes")
    else:
        print("ℹ️ Skipping PostgreSQL-specific indexes (using SQLite)")


def reverse_postgresql_indexes(apps, schema_editor):
    """Remove PostgreSQL-specific indexes"""
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            'DROP INDEX IF EXISTS recipe_translation_name_trgm_idx;')
        schema_editor.execute('DROP EXTENSION IF EXISTS pg_trgm;')


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_add_discovery_cache'),
    ]

    operations = [
        # Create PostgreSQL-specific indexes using Python function
        migrations.RunPython(
            create_postgresql_indexes,
            reverse_postgresql_indexes
        ),

        # Add index for fast pending/in-progress translation queries (both databases)
        migrations.AddIndex(
            model_name='recipetranslation',
            index=models.Index(
                fields=['status', 'language'],
                name='recipe_trans_status_lang_idx',
            ),
        ),

        # Add composite index for fast canonical recipe + language lookups (both databases)
        migrations.AddIndex(
            model_name='recipetranslation',
            index=models.Index(
                fields=['canonical_recipe', 'language', 'status'],
                name='recipe_trans_recipe_lang_status_idx'
            ),
        ),
    ]
