# Generated by Django 4.2.7 on 2025-10-23 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_add_allergens_field'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='recipetranslation',
            name='recipe_trans_status_lang_idx',
        ),
        migrations.RemoveIndex(
            model_name='recipetranslation',
            name='recipe_trans_recipe_lang_status_idx',
        ),
    ]
