# Generated by Django 4.2.7 on 2025-10-30 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0012_remove_recipetranslation_recipe_trans_status_lang_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRecipeGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipe_list', models.TextField(help_text='Recipe names to generate, one per line. Example:\nChicken Parmesan\nBeef Stroganoff\nVegetarian Lasagna')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partially Completed')], default='pending', max_length=20)),
                ('total_recipes', models.IntegerField(default=0)),
                ('completed_recipes', models.IntegerField(default=0)),
                ('failed_recipes', models.IntegerField(default=0)),
                ('results', models.JSONField(blank=True, default=dict, help_text='Details about each recipe: {"recipe_name": {"status": "success/failed", "recipe_id": "...", "error": "..."}}')),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(help_text='Admin who created this bulk generation job', on_delete=django.db.models.deletion.CASCADE, related_name='bulk_recipe_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Recipe Generation Job',
                'verbose_name_plural': 'Bulk Recipe Generation Jobs',
                'db_table': 'bulk_recipe_generation_jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='bulk_recipe_status_5de7bc_idx'), models.Index(fields=['created_by', '-created_at'], name='bulk_recipe_created_f394be_idx')],
            },
        ),
    ]
