# Generated by Django 4.2.7 on 2025-09-22 16:08

from django.db import migrations, models
import random
import string


def generate_collaboration_keys(apps, schema_editor):
    """Generate collaboration keys for existing users"""
    User = apps.get_model('users', 'User')

    colors = ['#4F46E5', '#7C3AED', '#DC2626', '#059669', '#D97706', '#0284C7']

    for i, user in enumerate(User.objects.all()):
        # Generate unique collaboration key
        while True:
            key = ''.join(random.choices(string.digits, k=6))
            if not User.objects.filter(collaboration_key=key).exists():
                break

        user.collaboration_key = key
        user.personal_color = colors[i % len(colors)]
        user.save()


def reverse_collaboration_keys(apps, schema_editor):
    """Remove collaboration keys"""
    User = apps.get_model('users', 'User')
    User.objects.update(collaboration_key=None, personal_color='#4F46E5')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='collaboration_key',
            field=models.CharField(
                blank=True, help_text='6-digit unique key for sharing shopping lists', max_length=6, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='personal_color',
            field=models.CharField(default='#4F46E5', max_length=7),
        ),
        migrations.AddField(
            model_name='user',
            name='shopping_role',
            field=models.CharField(choices=[('creator', 'List Creator'), ('collaborator', 'Collaborator'), (
                'both', 'Both Creator and Collaborator')], default='both', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['collaboration_key'], name='users_user_collabor_9a8f3a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(
                fields=['shopping_role'], name='users_user_shoppin_e9d8c2_idx'),
        ),
        migrations.RunPython(generate_collaboration_keys,
                             reverse_collaboration_keys),
    ]
