# Generated by Django 4.2.7 on 2025-09-23 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250922_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='weight_unit',
            field=models.CharField(
                choices=[('kg', 'Kilograms'), ('lbs', 'Pounds')],
                default='kg',
                help_text='Preferred weight unit for display',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='volume_unit',
            field=models.CharField(
                choices=[('liters', 'Liters'), ('gallons', 'Gallons')],
                default='liters',
                help_text='Preferred volume unit for display',
                max_length=10
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='time_format',
            field=models.CharField(
                choices=[('24h', '24 Hour'), ('12h', '12 Hour (AM/PM)')],
                default='24h',
                help_text='Preferred time format for display',
                max_length=5
            ),
        ),
    ]
