# Generated by Django 4.2.7 on 2025-09-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20250923_1159'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='users_collabo_06aa1c_idx',
            old_name='users_user_collabor_9a8f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='users_shoppin_e2c4b0_idx',
            old_name='users_user_shoppin_e9d8c2_idx',
        ),
    ]
