# Generated by Django 4.2.7 on 2025-10-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_gender_userpreferences'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_seen_guides',
            field=models.JSONField(blank=True, default=list, help_text='List of page guides the user has completed (e.g. ["dashboard", "shopping", "inventory"])'),
        ),
    ]
