# Generated by Django 4.2.16 on 2026-05-29 06:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_has_seen_guides'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_rate_limited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='last_ai_request_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nutrition_logs_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rate_limit_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='recipe_generations_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='suspicious_activity_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='translations_today',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='url_scrapes_today',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AIRequestLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_type', models.CharField(max_length=50)),
                ('endpoint', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('user_agent', models.TextField(blank=True)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_request_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='ai_request__user_id_cd31f1_idx'), models.Index(fields=['ip_address', '-created_at'], name='ai_request__ip_addr_a44736_idx')],
            },
        ),
    ]
