# Generated by Django 4.2.7 on 2025-10-14 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_key', models.CharField(db_index=True, help_text='Unique ingredient key from IML (e.g., tomatoes-red-ripe)', max_length=200, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('source', models.CharField(help_text='Data source: usda, openfoodfacts, brave', max_length=50)),
                ('common_units', models.JSONField(default=dict, help_text='Common units by type: {weight: [g, kg], volume: [ml, L], count: [pcs]}')),
                ('unit_conversions', models.JSONField(default=dict, help_text='Unit conversions: {1_pcs: 150g, 1_cup: 180g}')),
                ('shelf_life', models.JSONField(default=dict, help_text='Shelf life in days: {room_temperature: 2, refrigerator: 7, freezer: 180}')),
                ('storage_recommendations', models.JSONField(default=dict, help_text='Storage recommendations: {recommended: refrigerator, temperature_range: 4-10°C}')),
                ('nutrition_per_100g', models.JSONField(default=dict, help_text='Nutrition per 100g: {calories: 18, protein: 0.9, fat: 0.2, carbs: 3.9, ...}')),
                ('metadata', models.JSONField(default=dict, help_text='Full IML data for reference')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ingredient Cache',
                'verbose_name_plural': 'Ingredient Cache',
                'db_table': 'ingredients_cache',
            },
        ),
        migrations.CreateModel(
            name='IngredientTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], max_length=2)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(default=list, help_text='Alternative names: [tomato, red tomato]')),
                ('storage_tips', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.ingredientcache')),
            ],
            options={
                'verbose_name': 'Ingredient Translation',
                'verbose_name_plural': 'Ingredient Translations',
                'db_table': 'ingredient_translations',
            },
        ),
        migrations.AddIndex(
            model_name='ingredientcache',
            index=models.Index(fields=['ingredient_key'], name='ingredients_ingredi_a57960_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientcache',
            index=models.Index(fields=['category'], name='ingredients_categor_7566b2_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredientcache',
            index=models.Index(fields=['source'], name='ingredients_source_c65ed0_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredienttranslation',
            index=models.Index(fields=['language', 'name'], name='ingredient__languag_ae839c_idx'),
        ),
        migrations.AddIndex(
            model_name='ingredienttranslation',
            index=models.Index(fields=['name'], name='ingredient__name_d75797_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ingredienttranslation',
            unique_together={('ingredient', 'language')},
        ),
    ]
