# Generated by Django 4.2.7 on 2025-10-20 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookingTermCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_english', models.CharField(db_index=True, help_text='English cooking term', max_length=200, unique=True)),
                ('term_english_normalized', models.CharField(db_index=True, help_text='Normalized English term for matching', max_length=200)),
                ('term_type', models.CharField(blank=True, help_text='Type of term: technique, tool, ingredient, method, etc.', max_length=50)),
                ('category', models.CharField(blank=True, help_text='Category: heat_method, cutting_method, mixing_method, etc.', max_length=100)),
                ('definition', models.TextField(blank=True, help_text='Definition of the cooking term')),
                ('usage_frequency', models.CharField(blank=True, help_text='How common: very_common, common, uncommon, rare', max_length=20)),
                ('difficulty_level', models.CharField(blank=True, help_text='Skill level: beginner, intermediate, advanced', max_length=20)),
                ('confidence_score', models.IntegerField(default=0, help_text='Translation confidence (0-100)')),
                ('verified', models.BooleanField(default=False, help_text='Whether translation has been verified')),
                ('last_synced', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cooking Term',
                'verbose_name_plural': 'Cooking Terms',
                'db_table': 'cooking_terms_cache',
            },
        ),
        migrations.CreateModel(
            name='CookingTermTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], max_length=2)),
                ('translation', models.CharField(db_index=True, help_text='Translated term', max_length=200)),
                ('verification_status', models.CharField(default='unverified', help_text='Verification status: unverified, ai_verified, web_verified, human_verified', max_length=20)),
                ('alternative_translations', models.JSONField(default=list, help_text='Alternative translations: [alt1, alt2]')),
                ('cultural_notes', models.TextField(blank=True, help_text='Cultural or usage notes for this translation')),
                ('source', models.CharField(blank=True, help_text='Translation source: gemini, groq, web, manual', max_length=50)),
                ('confidence_score', models.IntegerField(default=0, help_text='Translation confidence (0-100)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.cookingtermcache')),
            ],
            options={
                'verbose_name': 'Cooking Term Translation',
                'verbose_name_plural': 'Cooking Term Translations',
                'db_table': 'cooking_term_translations',
            },
        ),
        migrations.AddIndex(
            model_name='cookingtermcache',
            index=models.Index(fields=['term_english'], name='cooking_ter_term_en_3a8d3f_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingtermcache',
            index=models.Index(fields=['term_english_normalized'], name='cooking_ter_term_en_85c8d6_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingtermcache',
            index=models.Index(fields=['category'], name='cooking_ter_categor_bc6e88_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingtermcache',
            index=models.Index(fields=['term_type'], name='cooking_ter_term_ty_c3265b_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingtermtranslation',
            index=models.Index(fields=['language_code', 'translation'], name='cooking_ter_languag_ca65eb_idx'),
        ),
        migrations.AddIndex(
            model_name='cookingtermtranslation',
            index=models.Index(fields=['translation'], name='cooking_ter_transla_cce91a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cookingtermtranslation',
            unique_together={('term', 'language_code')},
        ),
    ]
