# Generated by Django for MenuMine AI - Sprint 1
# Import History tracking for IML and CookLingo data imports

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cookingtermcache_cookingtermtranslation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('import_type', models.CharField(
                    choices=[
                        ('iml', 'IML Ingredients'),
                        ('cooklingo', 'CookLingo Terms'),
                        ('iml_delete', 'IML Delete All'),
                        ('cooklingo_delete', 'CookLingo Delete All'),
                    ],
                    max_length=50,
                    db_index=True,
                    help_text='Type of import operation performed'
                )),
                ('source_file', models.CharField(
                    max_length=255,
                    blank=True,
                    help_text='Name of the source file (for SQLite imports)'
                )),
                ('records_imported', models.IntegerField(
                    default=0,
                    help_text='Number of new records imported'
                )),
                ('records_updated', models.IntegerField(
                    default=0,
                    help_text='Number of existing records updated'
                )),
                ('records_failed', models.IntegerField(
                    default=0,
                    help_text='Number of records that failed to import'
                )),
                ('imported_by', models.CharField(
                    max_length=100,
                    help_text='Username or system that performed the import'
                )),
                ('imported_at', models.DateTimeField(
                    auto_now_add=True,
                    db_index=True,
                    help_text='When the import was performed'
                )),
                ('status', models.CharField(
                    max_length=50,
                    choices=[
                        ('success', 'Success'),
                        ('partial', 'Partial Success'),
                        ('failed', 'Failed'),
                    ],
                    default='success',
                    help_text='Overall status of the import operation'
                )),
                ('error_log', models.TextField(
                    blank=True,
                    help_text='Detailed error messages (JSON format)'
                )),
                ('summary', models.JSONField(
                    default=dict,
                    blank=True,
                    help_text='Additional metadata about the import'
                )),
            ],
            options={
                'db_table': 'import_history',
                'verbose_name': 'Import History',
                'verbose_name_plural': 'Import History',
                'ordering': ['-imported_at'],
                'indexes': [
                    models.Index(
                        fields=['import_type', '-imported_at'], name='import_type_time_idx'),
                    models.Index(fields=['-imported_at'],
                                 name='import_time_idx'),
                    models.Index(fields=['status'], name='import_status_idx'),
                ],
            },
        ),
    ]
