# Generated by Django for MenuMine AI - Sprint 1
# Add validation fields to IngredientCache for amount checking

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_import_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientcache',
            name='typical_amount_min',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Typical minimum amount in grams for validation'
            ),
        ),
        migrations.AddField(
            model_name='ingredientcache',
            name='typical_amount_max',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Typical maximum amount in grams for validation'
            ),
        ),
        migrations.AddField(
            model_name='ingredientcache',
            name='typical_amount_avg',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Typical average amount in grams'
            ),
        ),
        migrations.AddField(
            model_name='ingredientcache',
            name='max_per_serving',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Maximum reasonable amount per serving in grams'
            ),
        ),
        migrations.AddField(
            model_name='ingredientcache',
            name='warning_threshold',
            field=models.IntegerField(
                null=True,
                blank=True,
                help_text='Threshold for suspicious amounts that should warn user (in grams)'
            ),
        ),
    ]
