# Generated by Django 4.2.7 on 2025-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_validation_fields_to_ingredientcache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
