# Generated by Django 4.2.7 on 2025-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_validation_fields_to_ingredientcache'),
    ]

    operations = [
        # Skip UUID to BigAutoField conversion for PostgreSQL
        # The table is created fresh with BigAutoField in Postgres
        # This migration only applies to SQLite -> SQLite upgrades
    ]
