# Generated by Django 4.2.7 on 2025-10-31 16:53

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_validation_fields_to_ingredientcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Update title (e.g., "New Recipe Builder Feature")', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the update or upcoming feature')),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('ru', 'Russian')], db_index=True, default='en', help_text='Language of this update', max_length=2)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('upcoming', 'Upcoming')], default='completed', help_text='Whether this update is completed or upcoming', max_length=20)),
                ('version', models.CharField(blank=True, help_text='Version number (e.g., "2.1.0") - optional', max_length=20, null=True)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When this update was/will be published')),
                ('is_published', models.BooleanField(default=True, help_text='Whether this update is visible to users')),
                ('is_featured', models.BooleanField(default=False, help_text='Featured updates appear at the top with special styling')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Update',
                'verbose_name_plural': 'App Updates',
                'db_table': 'app_updates',
                'ordering': ['-publish_date', '-created_at'],
                'indexes': [models.Index(fields=['language', 'is_published'], name='app_updates_languag_a020d0_idx'), models.Index(fields=['publish_date'], name='app_updates_publish_e71eef_idx'), models.Index(fields=['status'], name='app_updates_status_1293c1_idx')],
            },
        ),
    ]
