# Generated by Django 4.2.7 on 2025-10-27 23:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LegalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('copyright', 'Copyright Notice'), ('rcip', 'RCIP License')], max_length=20, unique=True)),
                ('content', models.TextField(help_text='Markdown content of the document')),
                ('version', models.CharField(help_text='Document version (e.g., 2.0)', max_length=20)),
                ('effective_date', models.DateField(help_text='Date when this version became effective')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Current active version')),
                ('updated_by', models.CharField(blank=True, help_text='Admin username who updated the document', max_length=100)),
            ],
            options={
                'verbose_name': 'Legal Document',
                'verbose_name_plural': 'Legal Documents',
                'db_table': 'legal_documents',
                'ordering': ['document_type', '-effective_date'],
                'indexes': [models.Index(fields=['document_type', 'is_active'], name='legal_docum_documen_6f1007_idx'), models.Index(fields=['-effective_date'], name='legal_docum_effecti_8a0728_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalAcceptance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('terms_version', models.CharField(default='2.0', max_length=20)),
                ('privacy_version', models.CharField(default='2.0', max_length=20)),
                ('cookie_version', models.CharField(default='2.0', max_length=20)),
                ('accepted_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('consent_method', models.CharField(choices=[('registration', 'During Registration'), ('update', 'Policy Update Acceptance'), ('manual', 'Manual Acceptance')], default='registration', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_acceptances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legal Acceptance',
                'verbose_name_plural': 'Legal Acceptances',
                'db_table': 'legal_acceptances',
                'ordering': ['-accepted_at'],
                'indexes': [models.Index(fields=['user', '-accepted_at'], name='legal_accep_user_id_b67cc6_idx'), models.Index(fields=['accepted_at'], name='legal_accep_accepte_5a111b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('export_format', models.CharField(choices=[('json', 'JSON'), ('csv', 'CSV')], default='json', max_length=10)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('downloaded', models.BooleanField(default=False)),
                ('downloaded_at', models.DateTimeField(blank=True, null=True)),
                ('download_count', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'data_export_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', '-requested_at'], name='data_export_user_id_214559_idx'), models.Index(fields=['status'], name='data_export_status_6fb662_idx')],
            },
        ),
        migrations.CreateModel(
            name='CookieConsent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(blank=True, help_text='For anonymous users before registration', max_length=255, null=True, unique=True)),
                ('consent_type', models.CharField(choices=[('all', 'Accept All Cookies'), ('essential', 'Essential Cookies Only'), ('custom', 'Custom Selection'), ('rejected', 'Rejected All Non-Essential')], default='essential', max_length=20)),
                ('essential_cookies', models.BooleanField(default=True, help_text='Required for site functionality - cannot be disabled')),
                ('functional_cookies', models.BooleanField(default=False, help_text='Remember preferences and settings')),
                ('analytics_cookies', models.BooleanField(default=False, help_text='Help us understand site usage')),
                ('performance_cookies', models.BooleanField(default=False, help_text='Optimize site performance')),
                ('gpc_signal_detected', models.BooleanField(default=False, help_text='Whether user has GPC enabled (auto-reject tracking)')),
                ('consented_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cookie_consent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cookie Consent',
                'verbose_name_plural': 'Cookie Consents',
                'db_table': 'cookie_consents',
                'ordering': ['-updated_at'],
                'indexes': [models.Index(fields=['user'], name='cookie_cons_user_id_cb7e0c_idx'), models.Index(fields=['session_id'], name='cookie_cons_session_0a2df5_idx'), models.Index(fields=['-updated_at'], name='cookie_cons_updated_832ce8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AccountDeletionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending (Grace Period)'), ('processing', 'Processing Deletion'), ('completed', 'Completed'), ('cancelled', 'Cancelled by User')], default='pending', max_length=20)),
                ('grace_period_ends', models.DateTimeField(help_text='Date when account will be permanently deleted')),
                ('reason', models.TextField(blank=True, help_text='Optional: Why user is leaving')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_deletion_requests',
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='account_del_user_id_85393b_idx'), models.Index(fields=['grace_period_ends'], name='account_del_grace_p_a93c5b_idx')],
            },
        ),
    ]
