# Generated by Django 4.2.7 on 2025-10-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='legaldocument',
            options={'ordering': ['document_type', 'language_code', '-effective_date'], 'verbose_name': 'Legal Document', 'verbose_name_plural': 'Legal Documents'},
        ),
        migrations.RemoveIndex(
            model_name='legaldocument',
            name='legal_docum_documen_6f1007_idx',
        ),
        migrations.AddField(
            model_name='legaldocument',
            name='language_code',
            field=models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], default='en', help_text='Language of the document (en, ru, he)', max_length=5),
        ),
        migrations.AlterField(
            model_name='legaldocument',
            name='document_type',
            field=models.CharField(choices=[('terms', 'Terms of Service'), ('privacy', 'Privacy Policy'), ('cookies', 'Cookie Policy'), ('copyright', 'Copyright Notice'), ('rcip', 'RCIP License')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='legaldocument',
            unique_together={('document_type', 'language_code')},
        ),
        migrations.AddIndex(
            model_name='legaldocument',
            index=models.Index(fields=['document_type', 'language_code', 'is_active'], name='legal_docum_documen_0254e9_idx'),
        ),
    ]
