# Generated by Django 4.2.16 on 2026-05-29 06:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0002_alter_legaldocument_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('language_code', models.CharField(choices=[('en', 'English'), ('ru', 'Russian'), ('he', 'Hebrew')], help_text='Language of the content (en, ru, he)', max_length=5, unique=True)),
                ('title', models.CharField(help_text='Page title (e.g., "About Us", "О нас", "אודותינו")', max_length=200)),
                ('content', models.TextField(help_text='Markdown content of the page')),
                ('version', models.CharField(default='1.0', help_text='Content version (e.g., 1.0, 1.1)', max_length=20)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description', max_length=300)),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords (comma-separated)', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this version currently active?')),
                ('updated_by', models.CharField(blank=True, help_text='Admin username who updated the content', max_length=100)),
                ('word_count', models.IntegerField(default=0, help_text='Approximate word count (auto-calculated)')),
            ],
            options={
                'verbose_name': 'About Page',
                'verbose_name_plural': 'About Pages',
                'db_table': 'about_pages',
                'ordering': ['language_code', '-updated_at'],
                'indexes': [models.Index(fields=['language_code', 'is_active'], name='about_pages_languag_b80c93_idx'), models.Index(fields=['-updated_at'], name='about_pages_updated_2bed80_idx')],
            },
        ),
    ]
