# Generated by Django 4.2.7 on 2025-10-12 10:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shopping', '0015_alter_inventory_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0005_add_archive_to_user_recipe'),
        ('users', '0006_add_gender_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserNutritionSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='nutrition_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('ai_coach_enabled', models.BooleanField(default=False, help_text='Master toggle for AI nutrition coach')),
                ('allow_recipes_access', models.BooleanField(default=False, help_text="Allow AI to view and suggest from user's recipes")),
                ('allow_inventory_access', models.BooleanField(default=False, help_text="Allow AI to view user's inventory items")),
                ('allow_shopping_access', models.BooleanField(default=False, help_text='Allow AI to view shopping patterns')),
                ('allow_personal_data_access', models.BooleanField(default=False, help_text='Master toggle for personal profile data')),
                ('allow_weight_data', models.BooleanField(default=False, help_text='Allow AI to see weight data')),
                ('allow_height_data', models.BooleanField(default=False, help_text='Allow AI to see height data')),
                ('allow_age_data', models.BooleanField(default=False, help_text='Allow AI to see age/birth date')),
                ('allow_gender_data', models.BooleanField(default=False, help_text='Allow AI to see gender data')),
                ('allow_activity_level', models.BooleanField(default=False, help_text='Allow AI to see activity level')),
                ('allow_health_conditions', models.BooleanField(default=False, help_text='Allow AI to see dietary restrictions and allergies')),
                ('goal_mode', models.CharField(choices=[('manual', 'Manual - I set my own goals'), ('ai_calculated', 'AI Calculated - Based on my profile')], default='manual', help_text='How nutrition goals are determined', max_length=20)),
                ('manual_calories_goal', models.IntegerField(blank=True, help_text='Daily calorie goal (manual mode)', null=True, validators=[django.core.validators.MinValueValidator(500)])),
                ('manual_protein_goal', models.IntegerField(blank=True, help_text='Daily protein goal in grams (manual mode)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manual_carbs_goal', models.IntegerField(blank=True, help_text='Daily carbs goal in grams (manual mode)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('manual_fat_goal', models.IntegerField(blank=True, help_text='Daily fat goal in grams (manual mode)', null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('coaching_frequency', models.CharField(choices=[('daily', 'Daily check-ins'), ('weekly', 'Weekly summaries'), ('never', 'No coaching messages')], default='daily', help_text='How often AI coach provides feedback', max_length=20)),
                ('coaching_style', models.CharField(choices=[('supportive', 'Supportive & Encouraging'), ('strict', 'Strict & Disciplined'), ('balanced', 'Balanced Approach')], default='supportive', help_text='AI coaching personality', max_length=20)),
                ('track_calories', models.BooleanField(default=True)),
                ('track_protein', models.BooleanField(default=True)),
                ('track_carbs', models.BooleanField(default=False)),
                ('track_fat', models.BooleanField(default=False)),
                ('track_meal_timing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Nutrition Settings',
                'verbose_name_plural': 'User Nutrition Settings',
                'db_table': 'user_nutrition_settings',
            },
        ),
        migrations.CreateModel(
            name='NutritionEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='Date when food was consumed')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner'), ('snack', 'Snack')], help_text='Which meal this entry belongs to', max_length=20)),
                ('time', models.TimeField(blank=True, help_text='Time when food was consumed', null=True)),
                ('entry_type', models.CharField(choices=[('manual', 'Manual Entry'), ('recipe', 'From Recipe'), ('product', 'From Inventory Product'), ('ai_suggested', 'AI Suggested')], default='manual', help_text='How this entry was created', max_length=20)),
                ('food_name', models.CharField(help_text='Name of the food/dish', max_length=200)),
                ('portion_size', models.DecimalField(decimal_places=2, help_text='Amount consumed', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('portion_unit', models.CharField(default='grams', help_text='Unit of measurement (grams, ml, pieces, serving, etc.)', max_length=50)),
                ('calories', models.DecimalField(decimal_places=2, help_text='Total calories', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('protein', models.DecimalField(decimal_places=2, help_text='Protein in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('carbs', models.DecimalField(decimal_places=2, help_text='Carbohydrates in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fat', models.DecimalField(decimal_places=2, help_text='Fat in grams', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fiber', models.DecimalField(blank=True, decimal_places=2, help_text='Fiber in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, help_text='Sugar in grams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sodium', models.DecimalField(blank=True, decimal_places=2, help_text='Sodium in milligrams', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('notes', models.TextField(blank=True, help_text='Optional notes about the meal')),
                ('photo', models.ImageField(blank=True, help_text='Optional photo of the meal', null=True, upload_to='nutrition_photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_logs', to='shopping.inventory')),
                ('recipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nutrition_logs', to='recipes.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nutrition Entry',
                'verbose_name_plural': 'Nutrition Entries',
                'db_table': 'nutrition_entries',
                'ordering': ['-date', '-time', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='nutrition_e_user_id_7c2739_idx'), models.Index(fields=['user', 'meal_type'], name='nutrition_e_user_id_89e9e8_idx'), models.Index(fields=['date', 'meal_type'], name='nutrition_e_date_24cdf5_idx'), models.Index(fields=['user', '-date'], name='nutrition_e_user_id_0dd511_idx')],
            },
        ),
    ]
