# Generated by Django 4.2.7 on 2025-09-22 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def copy_owner_to_creator(apps, schema_editor):
    """Copy owner field to creator field"""
    ShoppingList = apps.get_model('shopping', 'ShoppingList')
    for shopping_list in ShoppingList.objects.all():
        shopping_list.creator = shopping_list.owner
        shopping_list.save()


def copy_creator_to_owner(apps, schema_editor):
    """Reverse: copy creator field back to owner field"""
    ShoppingList = apps.get_model('shopping', 'ShoppingList')
    for shopping_list in ShoppingList.objects.all():
        shopping_list.owner = shopping_list.creator
        shopping_list.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0001_initial'),
    ]

    operations = [
        # Step 1: Create new collaborator model
        migrations.CreateModel(
            name='ShoppingListCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit', models.BooleanField(default=True)),
                ('can_add_items', models.BooleanField(default=True)),
                ('can_invite_others', models.BooleanField(default=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('shopping_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                 related_name='collaborators', to='shopping.shoppinglist')),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'shopping_list_collaborators',
            },
        ),
        migrations.AlterUniqueTogether(
            name='shoppinglistcollaborator',
            unique_together={('user', 'shopping_list')},
        ),

        # Step 2: Add new fields to existing models
        migrations.AddField(
            model_name='shoppinglist',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='is_collaborative',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='user_color',
            field=models.CharField(blank=True, max_length=7),
        ),

        # Step 3: Copy data from owner to creator
        migrations.RunPython(copy_owner_to_creator, copy_creator_to_owner),

        # Step 4: Make creator non-nullable now that it has data
        migrations.AlterField(
            model_name='shoppinglist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='created_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
