# Generated by Django 4.2.7 on 2025-09-22 16:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0002_auto_20250922_1909'),
    ]

    operations = [
        # Add the many-to-many relationship through the collaborator model
        migrations.AddField(
            model_name='shoppinglist',
            name='participants',
            field=models.ManyToManyField(related_name='participating_lists',
                                         through='shopping.ShoppingListCollaborator', to=settings.AUTH_USER_MODEL),
        ),

        # Remove old fields
        migrations.RemoveField(
            model_name='shoppinglist',
            name='shared_with',
        ),

        # Update ordering and indexes
        migrations.AlterModelOptions(
            name='shoppingitem',
            options={'ordering': ['-priority',
                                  '-created_at', 'category', 'name']},
        ),

        # Add new indexes
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(fields=['added_by'],
                               name='shopping_it_added_b_ef3e2b_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppingitem',
            index=models.Index(
                fields=['priority', '-created_at'], name='shopping_it_priorit_d8f9c1_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(
                fields=['is_collaborative'], name='shopping_li_is_coll_a9e1b2_idx'),
        ),
    ]
