# Generated by Django 4.2.7 on 2025-09-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0003_auto_20250922_1909'),
    ]

    operations = [
    ]
