# Generated by Django 4.2.7 on 2025-09-22 19:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0004_auto_20250922_2007'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shoppingitem',
            new_name='shopping_it_added_b_4f230c_idx',
            old_name='shopping_it_added_b_ef3e2b_idx',
        ),
        migrations.RenameIndex(
            model_name='shoppingitem',
            new_name='shopping_it_priorit_8cb490_idx',
            old_name='shopping_it_priorit_d8f9c1_idx',
        ),
        migrations.RenameIndex(
            model_name='shoppinglist',
            new_name='shopping_li_is_coll_0bbb31_idx',
            old_name='shopping_li_is_coll_a9e1b2_idx',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='deleted_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(
                fields=['creator', '-updated_at'], name='shopping_li_creator_59f442_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['deleted_at'],
                               name='shopping_li_deleted_97707b_idx'),
        ),
        migrations.AddIndex(
            model_name='shoppinglist',
            index=models.Index(fields=['deleted_by'],
                               name='shopping_li_deleted_ce9f1a_idx'),
        ),
    ]
