# Generated by Django 4.2.7 on 2025-09-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0005_remove_shoppinglist_shopping_li_owner_i_9f1c40_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingitem',
            name='weight_quantity',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text='Weight quantity in grams (converted to user preference on display)',
                max_digits=10
            ),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='liquid_quantity',
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                help_text='Liquid quantity in milliliters (converted to user preference on display)',
                max_digits=10
            ),
        ),
    ]
