# Generated by Django 4.2.7 on 2025-09-23 23:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0007_auto_20250923_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppinglist',
            name='permanently_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='permanently_deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='permanently_deleted_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
