# Generated by Django 4.2.7 on 2025-09-24 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0008_remove_shoppinglist_shopping_li_owner_i_9f1c40_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShoppingListOwnershipTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('creator_deleted', 'Creator Deleted List'), ('auto_cleanup', 'Auto Cleanup After 60 Days'), (
                    'manual_transfer', 'Manual Transfer')], default='creator_deleted', max_length=100)),
                ('transferred_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'shopping_list_ownership_transfers',
                'ordering': ['-transferred_at'],
            },
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='deletion_warning_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='deletion_warning_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='last_activity',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='shoppinglistcollaborator',
            name='items_added_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shoppinglistownershiptransfer',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='transferred_from_lists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shoppinglistownershiptransfer',
            name='shopping_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='ownership_transfers', to='shopping.shoppinglist'),
        ),
        migrations.AddField(
            model_name='shoppinglistownershiptransfer',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='transferred_to_lists', to=settings.AUTH_USER_MODEL),
        ),
    ]
