# Generated by Django 4.2.7 on 2025-09-24 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0009_shoppinglistownershiptransfer_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shoppinglist',
            name='shopping_li_owner_i_9f1c40_idx',
        ),
    ]
