# Generated by Django 4.2.7 on 2025-09-24 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0010_remove_shoppinglist_shopping_li_owner_i_9f1c40_idx'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE shopping_lists ADD COLUMN deletion_warning_sent BOOLEAN DEFAULT FALSE",
            reverse_sql="ALTER TABLE shopping_lists DROP COLUMN deletion_warning_sent"
        ),
        migrations.RunSQL(
            "ALTER TABLE shopping_lists ADD COLUMN deletion_warning_sent_at DATETIME",
            reverse_sql="ALTER TABLE shopping_lists DROP COLUMN deletion_warning_sent_at"
        ),
        migrations.RunSQL(
            "ALTER TABLE shopping_lists ADD COLUMN last_activity DATETIME",
            reverse_sql="ALTER TABLE shopping_lists DROP COLUMN last_activity"
        ),
    ]
