# Generated by Django 4.2.7 on 2025-09-24 07:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0011_add_missing_columns'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE shopping_list_ownership_transfers (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                shopping_list_id CHAR(32) NOT NULL,
                from_user_id CHAR(32),
                to_user_id CHAR(32) NOT NULL,
                reason VARCHAR(100) DEFAULT 'creator_deleted',
                transferred_at DATETIME NOT NULL,
                FOREIGN KEY (shopping_list_id) REFERENCES shopping_lists (id) ON DELETE CASCADE,
                FOREIGN KEY (from_user_id) REFERENCES users (id) ON DELETE SET NULL,
                FOREIGN KEY (to_user_id) REFERENCES users (id) ON DELETE CASCADE
            )
            """,
            reverse_sql="DROP TABLE shopping_list_ownership_transfers"
        ),
    ]
