# Generated by Django 4.2.7 on 2025-09-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0012_create_ownership_transfer_table'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE shopping_list_collaborators ADD COLUMN items_added_count INTEGER DEFAULT 0",
            reverse_sql="ALTER TABLE shopping_list_collaborators DROP COLUMN items_added_count"
        ),
    ]
