# Generated by Django 4.2.7 on 2025-10-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0014_add_enhanced_inventory_and_history'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'ordering': ['location', 'name'], 'verbose_name_plural': 'Inventory items'},
        ),
    ]
