# Generated by Django 4.2.7 on 2025-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0015_alter_inventory_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='expiration_source',
            field=models.CharField(choices=[('iml', 'From IML Data'), ('ai', 'AI Suggested'), ('manual', 'User Set')], default='manual', help_text='Source of expiration date calculation', max_length=20),
        ),
        migrations.AddField(
            model_name='inventory',
            name='ingredient_key',
            field=models.CharField(blank=True, db_index=True, help_text='Link to IML ingredient', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('volume', 'Volume'), ('count', 'Count'), ('cooking', 'Cooking Unit')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='conversion_applied',
            field=models.BooleanField(default=False, help_text='Whether unit conversion was applied'),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='custom_name',
            field=models.CharField(blank=True, help_text="If no IML match, store user's original text", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='ingredient_key',
            field=models.CharField(blank=True, db_index=True, help_text='Link to IML ingredient: tomatoes-red-ripe', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='match_confidence',
            field=models.FloatField(blank=True, help_text='Confidence score: 0.0-1.0', null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='match_status',
            field=models.CharField(choices=[('pending', 'Pending Match'), ('matched', 'Matched to IML'), ('no_match', 'No Match Found'), ('manual', 'Manually Linked')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='normalized_unit',
            field=models.CharField(blank=True, help_text='Normalized unit: tsp, tbsp, g, kg, ml, L, pcs', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='original_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Before conversion (if any)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='original_unit',
            field=models.CharField(blank=True, help_text="User's original: teaspoon, pieces, gramms", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='suggested_key',
            field=models.CharField(blank=True, help_text='AI suggestion before user confirms', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='shoppingitem',
            name='unit_type',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('volume', 'Volume'), ('count', 'Count'), ('cooking', 'Cooking Unit')], max_length=20, null=True),
        ),
    ]
