# Generated by Django 4.2.16 on 2025-10-21 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0017_add_missing_deletion_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='shoppinglist',
            new_name='shopping_li_creator_59f442_idx',
            old_name='shopping_li_creator_updated_idx',
        ),
    ]
