# Generated by Django 4.2.7 on 2025-10-22 12:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shopping', '0018_rename_shopping_li_creator_updated_idx_shopping_li_creator_59f442_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRecipeBrief',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inventory_hash', models.CharField(db_index=True, help_text='SHA256 hash of inventory state (items + quantities)', max_length=64)),
                ('language', models.CharField(choices=[('en', 'English'), ('he', 'Hebrew'), ('ru', 'Russian')], db_index=True, default='en', max_length=2)),
                ('inventory_snapshot', models.JSONField(help_text='Snapshot of inventory items at generation time')),
                ('recipes', models.JSONField(help_text='Array of generated recipe briefs with validation')),
                ('generation_params', models.JSONField(help_text='Parameters used: max_recipes, prioritize_expiring, etc.')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True, help_text='TTL: 24 hours from generation')),
                ('ai_model', models.CharField(default='gemini-2.0-flash-lite', help_text='AI model used for generation', max_length=50)),
                ('generation_time_ms', models.IntegerField(help_text='Time taken to generate (ms)')),
                ('view_count', models.IntegerField(default=0, help_text='How many times retrieved from cache')),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cached_recipe_briefs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inventory Recipe Brief Cache',
                'verbose_name_plural': 'Inventory Recipe Brief Caches',
                'db_table': 'inventory_recipe_briefs',
                'indexes': [models.Index(fields=['user', 'inventory_hash', 'language'], name='inventory_r_user_id_18ad56_idx'), models.Index(fields=['expires_at'], name='inventory_r_expires_260cf7_idx'), models.Index(fields=['user', 'generated_at'], name='inventory_r_user_id_e68bd8_idx')],
            },
        ),
    ]
