# Generated by Django 4.2.7 on 2025-10-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0020_add_multilang_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingitem',
            name='name_translations',
            field=models.JSONField(blank=True, default=dict, help_text='Translated names: {"en": "tomato", "ru": "помидор", "he": "עגבנייה"}'),
        ),
    ]
